# Generated by Django 5.0.6 on 2024-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingUnit',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('hours', models.SmallIntegerField(max_length=2)),
                ('period', models.SmallIntegerField(max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%m/')),
            ],
        ),
    ]
