# Generated by Django 5.0.6 on 2024-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingunit',
            name='hours',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingunit',
            name='period',
            field=models.SmallIntegerField(),
        ),
    ]
