# Generated by Django 5.0.6 on 2024-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_class_options_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingunit',
            name='picture',
        ),
        migrations.AddField(
            model_name='class',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
