# Generated by Django 5.0.6 on 2024-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_trainingunit_picture_class_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, choices=[('FML', 'Famalicão'), ('FRM', 'Freamunde'), ('PFR', 'Paços de Ferreira'), ('STR', 'Santo Tirso')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='dropout',
            field=models.BooleanField(default=False),
        ),
    ]
