# Generated by Django 5.0.6 on 2024-06-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_student_city_student_dropout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='my_class',
        ),
    ]
