# Generated by Django 5.0.6 on 2024-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename__class_student_my_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
