# Generated by Django 5.0.6 on 2024-06-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_class_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingunit',
            name='active',
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='all_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassesUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.trainingunit')),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.class')),
            ],
            options={
                'verbose_name': 'Classes Unit',
                'verbose_name_plural': 'Classes Units',
            },
        ),
        migrations.AddConstraint(
            model_name='classesunit',
            constraint=models.UniqueConstraint(fields=('unit', 'unit_class'), name='unique_unit_class_combination'),
        ),
    ]
